FROM jeluard/substrate-playground-template-base@sha256:dbc7947b9616a1864fc31b22c3dd45f996bb43f85c54e3d13d1fab320c3e528b

WORKDIR /home/substrate/workspace

RUN git clone https://github.com/substrate-developer-hub/substrate-node-template && \
    git clone https://github.com/substrate-developer-hub/substrate-front-end-template

RUN cd $HOME/workspace/substrate-front-end-template && yarn \
    && cd $HOME/workspace/substrate-node-template && cargo build --release