# The theia image used to build theia
# Based on https://github.com/theia-ide/theia-apps/blob/master/theia-docker/Dockerfile

FROM node:12
WORKDIR /home/theia
ADD package.json .
ADD lerna.json .
ADD theia-playground theia-playground
ADD theia-playground-extension theia-playground-extension
RUN yarn && \
    NODE_OPTIONS="--max-old-space-size=5120" yarn build